---
title: "Housing Burden Among Aging Populations"
format: dashboard
---

```{r}
library(tidyverse)
library(tigris)
library(ggplot2)
library(tidycensus)
library(shiny)
library(patchwork)
census_api_key("7941d5fa13fcf9df50ce662e6c460ae7b6ffc5da", install = TRUE)
```

```{r}

```

# NC Maps

```{r}
#| message: false


# load data
housing <- read_csv(here::here("data", "ACSPUMS1Y2021_all_counties.csv"))

# change names
colnames(housing) <- c(
"housing_unit_weight",
"person_weight",
"household_income",
"total_person_income",
"percent_gross_own",
"property_taxes",
"monthly_rent",
"age",
"percent_gross_rent",
"tenure",
"sex",
"american_indian",
"asian",
"white",
"black",
"pum_code",
"state",
"county"
)

# data cleaning
housing <- housing |> 
  mutate(
    rent_burden = if_else(percent_gross_rent >= 30, "Rent Burden", "Not Rent Burden")
  )

housing <- housing |> 
  mutate(
    owner_burden = if_else(percent_gross_own >= 30, "Owner Cost Burden", "Not Owner Cost Burden")
  )

housing <- housing |> 
  group_by(county, tenure) |> 
  mutate(
    n_pop = n(),
    percent_rent_burden_county = sum(rent_burden=="Rent Burden") / n_pop
  )

housing <- housing |> 
  group_by(county, tenure) |> 
  mutate(
    n_pop = n(),
    percent_owner_burden_county = sum(owner_burden=="Owner Cost Burden") / n_pop
  )

housing <- housing |>
  group_by(pum_code) |> 
  mutate(
    aging_rent_burden = sum(person_weight[rent_burden == "Rent Burden" & age >= 55]),
    aging_rent_burden_pct = aging_rent_burden / sum(person_weight[age >= 55])
  )

housing <- housing |>
  group_by(pum_code) |> 
  mutate(
    aging_owner_burden = sum(person_weight[owner_burden == "Owner Cost Burden" & age >= 55]),
    aging_owner_burden_pct = aging_owner_burden / sum(person_weight[age >= 55])
  )

#merging with tidycensus shape files
nc_puma <- tigris::pumas("NC", cb = TRUE, year = 2020, progress_bar = FALSE)
nc_map_data <- merge(nc_puma, housing, by.x = "PUMACE20", by.y = "pum_code")

#get county data
nc_counties <- tigris::counties("NC", cb = TRUE, year = 2020, progress_bar = FALSE)
cprc_counties <- c("Chatham County", "Durham County", "Orange County", "Wake County", "Moore County", "Lee County", "Johnston County")
cprc_county_data <- nc_counties[nc_counties$NAMELSAD %in% cprc_counties, ]
#map1 ------
map1 <- ggplot() +
  geom_sf(data = nc_map_data, aes(fill = aging_rent_burden_pct)) +
  scale_fill_viridis_c(labels = scales::percent_format()) +  # color scale
  geom_sf(data = cprc_county_data, fill = NA, color = "black", size = 0.5) +
  labs(title = "Rent Burden Rates",
       fill = "% Burdened by Rent Costs",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(hjust = 0, vjust = 1, face = "bold", size = 10),
        legend.position = "top",
        legend.box = "horizontal",
        plot.title = element_text(hjust = 0.5, face = "bold"), 
        plot.margin = margin(t = 20, r = 60, b = 0, l = 0))

#map 2 ------
map2 <- ggplot() +
  geom_sf(data = nc_map_data, aes(fill = aging_owner_burden_pct)) +
  scale_fill_viridis_c(labels = scales::percent_format()) +  # color scale
  geom_sf(data = cprc_county_data, fill = NA, color = "black", size = 0.5) +
  labs(title = "Home Owner Cost Burden Rates",
       fill = "% Burdened by Home Owner Costs",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        legend.title = element_text(hjust = 0, vjust = 1, face = "bold", size = 10),
        legend.position = "top",
        legend.box = "horizontal",
        plot.title = element_text(hjust = 0.5, face = "bold"), 
        plot.margin = margin(t = 20, r = 0, b = 0, l = 60))

#patchwork
footer_plot <- ggplot() +
  geom_blank() +
  theme_void() +
  annotate("text", x = 0, y = 0, label = "Source: American Community Survey 1-Year 2021 Public Use Microdata Survey", size = 2, color = "black", hjust = 0, vjust = 0)

patchwork <- (map1 + map2) / footer_plot
patchwork + plot_annotation(
  title="Housing Burden Among Ages 55+\nin NC Central Pines Regional Council Area", 
  subtitle = "Housing Burden is highest in parts of Wake and Durham Counties",
  theme = theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 15),
    plot.subtitle = element_text(hjust = 0.5, vjust = -1)))
```

# Graph 3

```{r}
filtered_data <- housing |>
filter(age >= 55 & (white == 1 | black == 1) & rent_burden %in% c("Rent Burden"))

agg_data_rent <- filtered_data |>
  group_by(county) |>
  summarise(
    white_agg = sum(white == 1),
    black_agg = sum(black == 1)
  ) |>
  pivot_longer(cols = c(white_agg, black_agg),
               names_to = "race",
               values_to = "agg_rent_burden")

dot_plot_rent <- ggplot(agg_data_rent, aes(x = county, y = agg_rent_burden, color = race)) +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  labs(x = "Counties", y = "Aggregate Rent Burden ", color = "Race") +
  ggtitle("Aggregate Rent Burden by Race for Individuals Over 55") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = c("black_agg" = "#64dae6", "white_agg" = "#63bcc1"),
                    labels = c("black_agg" = "Black Resident Rent Burden", "white_agg" = "White Resident Rent Burdened"))

dot_plot_rent
```

# Graph 4

```{r}
filtered_data <- housing |>
filter(age >= 55 & (white == 1 | black == 1) & owner_burden %in% c("Owner Cost Burden"))

agg_data_own <- filtered_data |>
  group_by(county) |>
  summarise(
    white_agg = sum(white == 1),
    black_agg = sum(black == 1)
  ) |>
  pivot_longer(cols = c(white_agg, black_agg),
               names_to = "race",
               values_to = "agg_own_burden")

dot_plot_own <- ggplot(agg_data_own, aes(x = county, y = agg_own_burden, color = race)) +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  labs(x = "Counties", y = "Aggregate Mortgage Burden ", color = "Race") +
  ggtitle("Aggregate Mortgage Burden by Race for Individuals Over 55") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_manual(values = c("black_agg" = "#a3dee8", "white_agg" = "#49497f"),
                    labels = c("black_agg" = "Black Resident Mortgage Burden", "white_agg" = "White Resident Mortgage Burden"))

dot_plot_own
```

# Graph 5

```{r}
library(dplyr)
library(ggplot2)

age_groups <- c("65 to 69 years", "70 to 74 years", "75 to 79 years", "80 to 84 years", "85 years & over")

stacked_housing <- housing |>
  mutate(age_group = case_when(
    age >= 65 & age <= 69 ~ "65 to 69 years",
    age >= 70 & age <= 74 ~ "70 to 74 years",
    age >= 75 & age <= 79 ~ "75 to 79 years",
    age >= 80 & age <= 84 ~ "80 to 84 years",
    age >= 85 ~ "85 years & over",
    TRUE ~ "Other"
  )) |>
  filter(age_group %in% age_groups)

population_counts <- stacked_housing |>
  group_by(county, age_group) |>
  summarise(n_pop = n())

custom_colors <- c("#a3dee8","#64dae6","#63bcc1","#736f91","#49497f")

stacked_bar <- ggplot(stacked_housing, aes(x = county, y = n_pop, fill = age_group)) +
  geom_bar(stat = "identity") +
  labs(x = "Counties in North Carolina", y = "Population", fill = "Age Group") +
  ggtitle("Different Age Groups in North Carolina Counties") +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.text.y = element_blank()) +
    scale_x_discrete(labels = c("Chatham & Lee Counties" = "Chatham & Lee", "Durham County" = "Durham", "Johnston County" = "Johnston", "Moore & Montgomery Counties" = "Moore & Montgomery", "Orange County" = "Orange", "Wake County" = "Wake"))


stacked_housing_filtered <- stacked_housing |>
  filter(county != "Wake County")

stacked_bar_zoomed <- ggplot(stacked_housing_filtered, aes(x = county, y = n_pop, fill = age_group)) +
  geom_bar(stat = "identity") +
   labs(x = "Counties", y = "Population", fill = "Age Group") +
  ggtitle("Different Age Groups in North Carolina Counties") +
  scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.text.y = element_blank()) +
    scale_x_discrete(labels = c("Chatham & Lee Counties" = "Chatham & Lee", "Durham County" = "Durham", "Johnston County" = "Johnston", "Moore & Montgomery Counties" = "Moore & Montgomery", "Orange County" = "Orange")) +
  scale_y_continuous(labels = scales::comma)

stacked_bar_zoomed
stacked_bar
```
